model:
  batch_size: 32
  channels: 3
  img_dim: 192  # Must be a factor of 16 (base UNet has 4 max pools in encoder)
  learning_rate: 0.000001
  max_epochs: 500
  weight_decay: 5.e-7
  resume: False  # Resume training from config.logging.model_save_dir/best_epoch.pth?

data:
  target_class: "water"
  train_image_dir: "/home/daniel/datasets/Agriculture-Vision-2021/train/images/rgb"
  train_labels_dir: "/home/daniel/datasets/Agriculture-Vision-2021/train/labels_filtered"
  val_image_dir: "/home/daniel/datasets/Agriculture-Vision-2021/val/images/rgb"
  val_labels_dir: "/home/daniel/datasets/Agriculture-Vision-2021/val/labels_filtered"
  train_val_test_split: [0.8, 0.1, 0.1]

logging:
  model_save_dir: "/home/daniel/saved_models/Agriculture-Vision-2021/models"
  plot_save_dir: "/home/daniel/saved_models/Agriculture-Vision-2021/plots"
  plot_every_n_epochs: 3